name: 'c3 - Custom Calendar Creator'
author: 'Boyd Kane @beyarkay'
description: 'Convert APIs to internet calendars with ease'
branding:
  icon: 'calendar'  
  color: 'orange'
inputs:
  glob:
    description: 'JS-compliant glob to list all calendar yaml files. Defaults to `calendars/*.yaml`.'
    required: false
    default: 'calendars/*.yaml'
outputs:
  file-paths:
    description: "A comma-separated list of paths to the generated ics files"
runs:
  using: 'node16'
  main: 'dist/index.js'
